### ISSUE TITLE
Toolbar icons not centered

### ISSUE THREAD

**Issue by kkiris** [Uiniel/zen-mods#10] opened 2024-12-12 05:42 UTC
The vertical strip of toolbar icons at the top of the sidebar are not centered when the Sidebar Enabled on Hover mod is enabled. 

| Mod enabled | Mod disabled |
| --- | --- |
| ![Zen Mod on](https://github.com/user-attachments/assets/c90fd094-0bd1-4883-9ef3-b4fb300fef6d) | ![Zen Mod off](https://github.com/user-attachments/assets/5755428f-6052-49e9-a686-3b6b47a33b3b)

**Comment by Uiniel** [comment] 2024-12-12 08:11
duplicate of #7

It is already fixed but might take some time until the mod is updated because updates need to be approved manually so I want to fix as many updates as possible at once

**Closed** 2024-12-12 08:12 UTC
Labels: duplicate, Sidebar Hover Mod

**Comment by kkiris** [comment] 2024-12-12 08:24
my bad, I checked for duplicates but only in open issues.

**Comment by Uiniel** [comment] 2024-12-12 09:27
fair, I reopened the issues and added a label to make it more clear until the mod is updated
